version: '3.4'

services:

  application:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - rabbitmq

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: "123456"
    ports:
      - "5432:5432"
   
  rabbitmq:
    image: rabbitmq:3-management
    ports:
        - "5672:5672"
        - "15672:15672"
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
