services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: "123456"
    ports:
      - "5454:5432"
   
  rabbitmq:
    image: rabbitmq:3-management
    ports:
        - "5680:5672"
        - "15680:15672"
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
  
